{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attemptRecovery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"resultHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"resultHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Once the recovery finished. Parameter is to show if the recovery succeeded or failed."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ubfoundation\/ubnetworktaskrecoveryoption\/attemptrecovery(resulthandler:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOption\/attemptRecovery(resultHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Attempt to recover from the error."}],"kind":"symbol","metadata":{"role":"symbol","title":"attemptRecovery(resultHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attemptRecovery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"resultHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12UBFoundation27UBNetworkTaskRecoveryOptionP07attemptD013resultHandleryySbc_tF","required":true,"modules":[{"name":"UBFoundation"}]},"hierarchy":{"paths":[["doc:\/\/UBFoundation\/documentation\/UBFoundation","doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOption"]]},"references":{"doc://UBFoundation/documentation/UBFoundation/UBNetworkTaskRecoveryOption/attemptRecovery(resultHandler:)":{"role":"symbol","title":"attemptRecovery(resultHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attemptRecovery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"resultHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Attempt to recover from the error."}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOption\/attemptRecovery(resultHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/ubfoundation\/ubnetworktaskrecoveryoption\/attemptrecovery(resulthandler:)"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkTaskRecoveryOption":{"role":"symbol","title":"UBNetworkTaskRecoveryOption","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkTaskRecoveryOption"}],"abstract":[{"type":"text","text":"An option to recover from a network task failure"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UBNetworkTaskRecoveryOption"}],"url":"\/documentation\/ubfoundation\/ubnetworktaskrecoveryoption"},"doc://UBFoundation/documentation/UBFoundation":{"role":"collection","title":"UBFoundation","abstract":[],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation"}}}