{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ubfoundation\/ubnetworktaskrecoveryoptions\/originalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOptions\/originalError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The original error that the object try to recover from"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"title":"originalError","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:12UBFoundation28UBNetworkTaskRecoveryOptionsV13originalErrors0G0_pvp","modules":[{"name":"UBFoundation"}]},"hierarchy":{"paths":[["doc:\/\/UBFoundation\/documentation\/UBFoundation","doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOptions"]]},"references":{"doc://UBFoundation/documentation/UBFoundation/UBNetworkTaskRecoveryOptions":{"role":"symbol","title":"UBNetworkTaskRecoveryOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkTaskRecoveryOptions"}],"abstract":[{"type":"text","text":"A set of options to recover from a network task failure"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UBNetworkTaskRecoveryOptions"}],"url":"\/documentation\/ubfoundation\/ubnetworktaskrecoveryoptions"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkTaskRecoveryOptions/originalError":{"role":"symbol","title":"originalError","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[{"type":"text","text":"The original error that the object try to recover from"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOptions\/originalError","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation\/ubnetworktaskrecoveryoptions\/originalerror"},"doc://UBFoundation/documentation/UBFoundation":{"role":"collection","title":"UBFoundation","abstract":[],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation"}}}